### ISSUE TITLE
Custom build args to revel package

### ISSUE THREAD

**Issue by viblo** [revel/cmd#10]
Please add a way to pass build flags when running / building with revel.

I have a number of (rest)services all using the same structure and then one web site made with revel. For the services I have a makefile which pass in date and git revision as ldflags, and a couple of build tags. 

In the end it becomes something like this

```
go install -tags="gm no_development" -ldflags "-X myorg/version.date $(DATE) -X myorg/version.version $(GITREV)"
```

I would like the same to be passed to our revel web site, so that I can reuse our existing code to track version and compilation date, and so that we can use 3rd party libs which use build tags.

**Comment by ptman** [comment]
I'd also link to change `-ldflags`, primarily to add `-s -w` in order to produce smaller binaries. Also `CGO_ENABLED`, would be interesting to set, but that is kept from the environment currently.

**Comment by ptman** [comment]
Actually, with the release of 0.12 I ran into an issue with https://github.com/revel/cmd/blob/master/harness/build.go#L83 as well. I use a distro provided go compiler and compile using CGO_ENABLED=0. This fails with

    go install net: open /usr/lib/go/pkg/linux_amd64/net.a: permission denied

unless I remove the `-i` argument. This should probably also be configurable.

**Comment by brendensoares** [comment]
Reviewing open issues, this seems like it would still be valuable. Now it's just a matter of coordinating a solution.

**Comment by notzippy** [comment]
Grouped with #81
