### ISSUE TITLE
Potential CSRF vulnerability associated with skeleton's catch-all route

### ISSUE THREAD

**Issue by MaxGabriel** [revel/cmd#105]
Hi, I noticed that the skeleton project includes a catch all route that maps any HTTP verb to the named controller/action:

```
*       /:controller/:action                    :controller.:action
```

This creates a potential security vulnerability by allowing `GET` requests to access state-changing routes while bypassing CSRF protection. I know Revel doesn't bundle CSRF protection, but the standard behavior is to only check CSRF tokens on state-changing methods like POST/PUT/DELETE, and not for GET/OPTIONS/HEAD/etc. This is the behavior of existing [Revel CSRF prevention libraries](https://github.com/cbonello/revel-csrf/blob/4dd0f3c795bb32e987fe8eea7f13078581ada38d/csrf.go#L53), and also for frameworks like Ruby on Rails, Yesod (Haskell), etc.

So I might have routing like this:

```
POST    /transfers                                  TransfersController.Create
*       /:controller/:action                    :controller.:action
```

and assume in my `TransfersController.Create` that some before interceptor has checked for a CSRF token, because I said that only POST maps to that method.  But an attacker could pretty easily guess my controller name/action, and do:

`GET /transferscontroller/create` to hit my endpoint, and because it's a GET request CSRF protection would have been bypassed, allowing the attacker to make transfers for any user visiting their site.

<hr>

This may sound theoretical if you're not familiar with CSRF attacks, but this exact same situation (using catch-all routes) led to huge security vulnerabilities for Ruby on Rails users, which researcher Egor Homakov [demonstrated by showing vulnerabilities](http://homakov.blogspot.com/2012/04/whitelist-your-routes-match-is-evil.html) in major sites like Tumblr and Justin.tv. Because of these vulnerabilities the Rails team [removed catch-all routes](https://github.com/rails/rails/issues/5964) ("match").

I think the Revel should:

1. At least remove catch-all routes from the skeleton project
2. Recommend to existing Revel users to remove the catch-all route
3. Consider dropping support for the catch-all route altogether.

Edit: I wasn't sure if this is the best repo for reporting this issue—I wasn't sure where exactly the Revel skeleton code is kept, but I know the command-line tool generates it.

**Comment by notzippy** [comment]
I totally agree that the catch all route does provide to much access and it isn't made clear enough in the documentation is an issue. 

The reasoning behind having it is for rapidly developing the project, then as part of the development process you should remove the "catch all" and add in all the routes defined. A thought of mine was to add a special revel command to rebuild the route file, and this process would remove all wildcard routes and replace them with the known endpoints. 

For now though, I will comment it out from the skeleton so it isn't there by default. 

P.s. you are in the right package the skeleton code is here.
P.p.s  Revel has the CSRF module here : https://github.com/revel/modules/blob/master/csrf/app/csrf.go

**Comment by MaxGabriel** [comment]
Cool, thanks for the quick response @notzippy.
