### ISSUE TITLE
DefaultValidationKeys generated with wrong line for multiline check

### ISSUE THREAD

**Issue by lokhman** [revel/cmd#119]
Consider the following code for validation:

```
20    ...
21    func (u *User) Validate(v *revel.Validation) {
22        v.Check(u.Username,
23            revel.ValidRequired(),
24            revel.ValidMinSize(3),
25            revel.ValidMaxSize(255))
26    }
27    ...
```

And this is what `revel/cmd` will generate in `tmp/main.go`:

```
revel.DefaultValidationKeys = map[string]map[int]string{ 
    "github.com/lokhman/revel-test/app/models.(*User).Validate": { 
        25: "u.Username",
    },
}
```

Line `25` from the generated code is the last line of a multiline statement, whereas `runtime.Caller(2)` from [`revel/validation.go`](https://github.com/revel/revel/blob/release/v0.19.0/validation.go#L216) will return line `22`. Due to this bug keys in validation errors become empty `""`.

(Revel 0.19; Go 1.9.2 linux/amd64)

**Comment by notzippy** [comment]
Yup that isnt right, I did a PR to fix a different issue where if controller.Render was multilined it would generate the wrong line number to extract the variable names. (see [here](https://github.com/revel/cmd/commit/2d4ccf289cd2e367eedca7f834fd497349b7f3c8)) If you change that back to left `Rparen` (and rebuild revel) does it work ? if so Revel will need to track both the right and left sides...

**Comment by lokhman** [comment]
@notzippy I think the problem was in using wrong method [here](https://github.com/revel/cmd/blob/master/harness/reflect.go#L601). If you replace `.End()` with `.Pos()` line gets identified correctly (tested on my machine). Made pull request, I don't see any possible issues with the change.

**Comment by notzippy** [comment]
Thanks I will check it out later tonight

**Comment by notzippy** [comment]
Merged
