### ISSUE TITLE
`revel` CLI command args vs flags

### ISSUE THREAD

**Issue by brendensoares** [revel/cmd#140]
This could apply to other `revel` commands as well, but we need to standardize and document the convention.

Each command, like `new` has required and optional fields.

- Required fields SHOULD directly follow the command in a defined sequenced eg. `revel new APPNAME`
- Optional fields SHOULD use flags eg. `-opt value` or `-opt=val` following the required fields.

**Comment by brendensoares** [comment]
I would argue that no matter how we collect options from the user, we still need to check for errors. If the app name is `myapp` and the target(aka mode) is `prod`, the `build` command still should make sure the value given matches the options. I can't imagine there being overlapping values between app name and target modes.

Also, flags can be just as ambiguous to a human, though it does help with option parsing. You have to either memorize order of required fields or flag names.

I think the real issue here is option ordering. With flags they can be in any order. However, that's a trade off with readability of the command, which can be subjective. I'm open to input on the topic, but I do like the simplicity that the legacy format affords at the cost of a learning curve.

**Comment by brendensoares** [comment]
Worth mentioning, Revel's cli follows the example of `go`'s:

```
go build foo -o bar -> flags: {} args: [foo, -o, bar]
go build -o bar foo -> flags: {o: bar} args: [foo] 
```

We should differentiate args vs flags. I'll update the issue title.

**Comment by notzippy** [comment]
The jessevdk/go-flags allows us to pull the "args" from the remainder of the command so the revel <command> [flags] [args] is actually easy to implement. All that needs to be done is add a validate method to the command so that the minimium commands are implemented
