### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ptman** [revel/cmd#142]
When running `revel version` outside of $GOPATH. Also, even though I tried to clean out sources, binaries and packages, and then installed revel using `go get -u -v github.com/revel/cmd/revel`, I get this from `revel version` (inside $GOPATH):

```
Revel executing: displays the Revel Framework and Go version

Revel Framework
Information not available (not on GOPATH)

Revel Command Utility Tool
Version 0.20.0-dev
Build Date 2018-02-06
Minimum Go Version >= go1.8
```

I'm sure it was built today, not 2018-02-06.

**Comment by amitsharma8891** [comment]
> When running `revel version` outside of $GOPATH. Also, even though I tried to clean out sources, binaries and packages, and then installed revel using `go get -u -v github.com/revel/cmd/revel`, I get this from `revel version` (inside $GOPATH):
> 
> ```
> Revel executing: displays the Revel Framework and Go version
> 
> Revel Framework
> Information not available (not on GOPATH)
> 
> Revel Command Utility Tool
> Version 0.20.0-dev
> Build Date 2018-02-06
> Minimum Go Version >= go1.8
> ```
> I'm sure it was built today, not 2018-02-06.

getting the same error.
