### ISSUE TITLE
BUG: wrong samples

### ISSUE THREAD

**Issue by pedromorgan** [revel/cmd#16]
The cmd currently shows

     github.com/revel/revel/samples/chat

instead of

       github.com/revel/samples/chat

eg
For example, to run the chat room sample application:

    revel run github.com/revel/revel/samples/chat dev

**Comment by brendensoares** [comment]
https://github.com/revel/cmd/blob/develop/revel/package.go#L20

They're been updated on the `develop` branch. Make sure you're using the same branch for all the repos.
