### ISSUE TITLE
When I create new revel project, it aborts with error

### ISSUE THREAD

**Issue by elijin0628328** [revel/cmd#170]
I wanna fix this.
When I create new revel project, it aborts with this output

Revel executing: create a skeleton Revel application
CRIT  17:55:06 command_config.go:286: Abort: could not create a Revel application outside of GOPATH.

**Comment by elijin0628328** [comment]
the command I excute is :  sudo revel new TestAPI
and I'm in GOPATH correctly.

**Comment by notzippy** [comment]
Do not run command as sudo, this is not needed

**Comment by notzippy** [comment]
No response, closing
