### ISSUE TITLE
why not use github.com/revel/revel/logger?

### ISSUE THREAD

**Issue by runner-mei** [revel/cmd#172]
why not use github.com/revel/revel/logger?
can  github.com/revel/cmd/logger remove, and replace with github.com/revel/revel/logger?

**Comment by Steve-hyas** [comment]
The reason for the package in both locations was so the two repositories were not dependent on each other.

**Comment by notzippy** [comment]
We do not want the cmd project dependent on the revel project. This causes a lot of headaches
