### ISSUE TITLE
Could not find import issue

### ISSUE THREAD

**Issue by cytown** [revel/cmd#174]
https://github.com/revel/cmd/blob/149f9f992be9b0957fb1ffeda43c14a123ceb43a/parser/reflect.go#L172

ERROR 18:11:02 reflect.go:172: Could not find import:                    path=os srcPath=/Users/demo/go/src/demo/app/controllers error="cannot find package \"os\" in any of:\n\t/usr/local/Cellar/go/1.12/libexec/src/os (from $GOROOT)\n\t/Users/demo/go/src/os (from $GOPATH)"

It exists for such a long time and not fixed.

Very annoy for build and package.

**Comment by notzippy** [comment]
I have rewritten the reflection package now and it should be resolved on develop branch
