### ISSUE TITLE
Can't create a new app on Windows

### ISSUE THREAD

**Issue by dre2004** [revel/cmd#175]
Hello,

I've just installed revel and I can't seem to create a new app.

OS: Windows 10 (1803)
Revel executing: displays the Revel Framework and Go version
WARN  21:03:59 version.go:71: Unable to extract version information from Revel library error,err=nil LOG15_ERROR="Normalized odd number of arguments by adding nil"
Revel Framework :       Unknown (0.21.0 remote master branch)
Revel Cmd       :       0.21.1  (0.21.1 remote master branch)
Revel Modules   :       Unknown (0.21.0 remote master branch)

go version go1.12.5 windows/amd64

When I try and run the command I get the following error:
`PS C:\code\go\src>revel new app
Revel executing: create a skeleton Revel application
CRIT  21:05:14 command_config.go:286: Abort: could not create a Revel application outside of GOPATH.`

My GOPATH is as follows
`GOPATH=C:\code\go;C:\Users\username\go;`

I've also tried removing my second GOPATH to no avail, revel is installed in c:\users\username\go

I've also tried executing the command from there with the same result.
`PS C:\Users\username\go\src> revel new gotodo
Revel executing: create a skeleton Revel application
CRIT  21:09:11 command_config.go:286: Abort: could not create a Revel application outside of GOPATH.
PS C:\Users\username\go>`

Here is the debug info
`PS C:\Users\username\go> revel /v new app
INFO  21:12:09   revel.go:94: Returned import path                     path=app buildpath=C:\\Users\\username\\go;C:\\code\\go;
Revel executing: create a skeleton Revel application
INFO  21:12:09  revel.go:104: InitGoPaths
INFO  21:12:09  revel.go:104: Source root                              gopath=C:\\Users\\username\\go;C:\\code\\go; bestpath=  path= cwd=C:\\Users\\username\\go
CRIT  21:12:09 command_config.go:286: Abort: could not create a Revel application outside of GOPATH.`

I've been using other applications with this same structure (two directories in gopath) without any issues (beego's bee command works fine). Am I missing something or is this a windows related issue?

**Comment by notzippy** [comment]
Are you sure your GOPATH is correct when you are trying that command ? The error ` GOPATH. PS C:\Users\username\go` indicates that the GOPATH is only  `C:\Users\username\go`

**Comment by dre2004** [comment]
Yes, that is the correct path.

I've tried the following permutations

- GOPATH=C:\Users\username\go;C:\code\go; ** This is what I have been using for months **
- GOPATH=C:\Users\username\go; ** I tried to create a new project within the src sub directory in this path **
- GOPATH=C:\code\go; ** I tried this as a last option by moving my go install to this directory **

In all three cases I got the same error (path obviously changing)

**Comment by notzippy** [comment]
I have rewritten the command line tool to address this issue
