### ISSUE TITLE
More helpers

### ISSUE THREAD

**Issue by pedromorgan** [revel/cmd#18]
Ok so here is me working on a new revel project..

and I kinda want more command..
eg 
new controller

> revel create controller Foo
> create app/foo.go{y}
> Controller Go Name = Foo(y} >
> Create view foo/index.html (y)

make it easy for boiler plate

**Comment by brendensoares** [comment]
This has been discussed and is [scheduled for v0.14](https://github.com/revel/revel/wiki/Roadmap#v014-see-issues). See the work in progress: https://github.com/kishorevaishnav/revelgen @kishorevaishnav
