### ISSUE TITLE
Failed to find Revel version

### ISSUE THREAD

**Issue by bencagri** [revel/cmd#184]
Hi guys, Im having a problem similar to revel/revel#1419 

```
cagrilocal:sozluk macbook$ revel run
ERROR 21:08:47 command_config.go:154: Failed to find Revel version:            error="open /Users/macbook/Development/go/pkg/mod/github.c/github.com/revel/revel/version.go: no such file or directory" path=/Users/macbook/Development/go/pkg/mod/github.c 
CRIT  21:08:47 command_config.go:155: Failed to fetch revel versions           error="Failed to parse Revel version error:[error 1:1: expected 'package', found 'EOF']" 
panic: Failed to fetch revel versions
```
this part doesnt seem correct to me
open /Users/macbook/Development **/go/pkg/mod/github.c/github.com/revel/revel/version.go** 
```
cagrilocal:sozluk macbook$ revel version
Revel executing: displays the Revel Framework and Go version
WARN  21:06:51 version.go:71: Unable to extract version information from Revel error,err=nil LOG15_ERROR="Normalized odd number of arguments by adding nil" 
WARN  21:06:51 version.go:71: Unable to extract version information from Revel Modules error="open /Users/macbook/Development/go/pkg/mod/github.com/revel/modules@v0.0.0-201github.com/revel/modules/version.go: no such file or directory" 
Revel Framework	:	Unknown	(0.21.0 remote master branch)
Revel Cmd	:	0.21.1	(0.21.1 remote master branch)
Revel Modules	:	Unknown	(0.21.0 remote master branch)

go version go1.12.7 darwin/amd64
```

I tried `go get -u github.com/revel/cmd` but still same. any ideas?  

Go env:
```
cagrilocal:model macbook$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/macbook/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/macbook/Development/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b3/8l0smqgd4591fb_bxj47jj940000gn/T/go-build137810273=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by lexxy23** [comment]
I also have this issue. Seems that the "path finder" for the revel command is broken:

`INFO  22:38:57   revel.go:94: Returned import path                     path=gitlab.com/ds2-internal/on-air buildpath=/Users/dstrauss/go 
INFO  22:38:57 command_config.go:301: Seeking app package                      app=gitlab.com/ds2-internal/on-air 
INFO  22:38:58 command_config.go:301: Seeking remote package                   using=gitlab.com/ds2-internal/on-air remote=github.com/revel/revel 
INFO  22:39:00 command_config.go:154: Fullpath to revel                        dir=/Users/dstrauss/go/pkg/mod/github.c 
ERROR 22:39:00 command_config.go:154: Failed to find Revel version:             error="open /Users/dstrauss/go/pkg/mod/github.c/github.com/revel/revel/version.go: no such file or directory" path=/Users/dstrauss/go/pkg/mod/github.c
INFO  22:39:00 command_config.go:314: Failed to parse Revel version error:     error="1:1: expected 'package', found 'EOF'" 
INFO  22:39:00 command_config.go:314: Stack                                    stack="[github.com/revel/cmd@v0.21.0/logger/utils.go:109 github.com/revel/cmd@v0.21.0/utils/build_error.go:22 github.com/revel/cmd@v0.21.0/model/command_config.go:314 github.com/revel/cmd@v0.21.0/model/command_config.go:154 revel/revel.go:94 runtime/proc.go:203 runtime/asm_amd64.s:1373]" 
CRIT  22:39:00 command_config.go:155: Failed to fetch revel versions           error="Failed to parse Revel version error:[error 1:1: expected 'package', found 'EOF']" 
panic: Failed to fetch revel versions

goroutine 1 [running]:
github.com/revel/cmd/logger.(*RevelLogger).Panic(0xc0001807c0, 0x152e4fd, 0x1e, 0xc00009e480, 0x2, 0x2)
        /Users/dstrauss/go/pkg/mod/github.com/revel/cmd@v0.21.0/logger/revel_logger.go:66 +0x9b
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc0001fa000, 0x35, 0x3)
        /Users/dstrauss/go/pkg/mod/github.com/revel/cmd@v0.21.0/model/command_config.go:155 +0x6af
main.main()
        /Users/dstrauss/go/pkg/mod/github.com/revel/cmd@v0.21.0/revel/revel.go:94 +0x160
`

**Comment by lexxy23** [comment]
On a side note: the latest develop seems to fix this issue:

* go get -u github.com/revel/cmd/revel@develop

and it finally works. Thx ;)
