### ISSUE TITLE
add `revel develop` command

### ISSUE THREAD

**Issue by pedromorgan** [revel/cmd#21]
the scenrrio is that..

One is hacking away at an application..
- and using stable master version

But one want to switch to the "develop" mode and thus 
- test revel stuff against future
- allow hacking of code etc..

So idea is to create command
- revel develop on = will grab latest revel branch and head
- revel develop off = will switch back to previous code
- this means all repos will have to switch..

so basically is doing a 
- git checkout revel/cmd
- git checkout revel/revel
- git checkout revel/modules
- git checkout revel/skeleton
  and switching between "stable" and next versions is the isea..

It a pain in the ass to do this manually

Also we need to chack whether we can create a remote head easy and integrate with github..
eg a 
go get gh/revel/skeletons = htttp ??
but now I wanna branch
and its a pain to have to go thru that caper..
so mabybe we can get revel to branch off automatically and help

**Comment by pedromorgan** [comment]
Scneraio

Am seriosuly hacking away at
https://github.com/daffodil/factory-planner

And I wannt to switch between the current version and next mixed version

Impossible..

So maaybe the next version is the one where we can make this possible..

**Comment by notzippy** [comment]
You can easily switch between versions by adjusting your gopath ev,

Open two shells 
Specify different gopaths and fetch revel in each
In one of the paths modify the checked out branch to develop for all revel repositories (git checkout -b develop), recompile (go build github.com/revel/cmd)
Now append your project path to each of the gopaths in the shells - or if your lazy symlink it.
Now you can test your app in both environments by running it in the appropriate shell window.

I would say **nay** to adding this to revel though, there is simply to many variables to control

**Comment by anonx** [comment]
@pedromorgan  Check it:
```sh
go get github.com/anonx/revdev
```
Use the following commands in your shell:
* `revdev on` to switch to develop branch
* `revdev off` to switch back to master

Everything will be checked out automatically and revel cmd will be recompiled.

**Comment by brendensoares** [comment]
I like @anonx's solution. Anything beyond that could get complex as @notzippy said.

**Comment by notzippy** [comment]
Once again with a monthly release cycle as a goal I am closing this issue as unnecessary.
