### ISSUE TITLE
Docs Issues

### ISSUE THREAD

**Issue by pedromorgan** [revel/cmd#29]
Can someone from the core team explain how I

-  go and hack revel/cmd/revel
ie how to modify go and go run..

Need to add this to the manual

- pattern/recipie for creating a new comand

**Comment by notzippy** [comment]
Does this help ?

A new file is created and a command instance is [instantiated](https://github.com/revel/cmd/blob/master/revel/clean.go#L10-L22).

An init method is added to assign the [Command.Run function](https://github.com/revel/cmd/blob/master/revel/clean.go#L24-L26)

The Command.Run function is called passing any additional arguments made on the command line

Commands are added to the []*Commands [here](https://github.com/revel/cmd/blob/master/revel/rev.go#L32-L39)

**Comment by pedromorgan** [comment]
lovely lovely....

I honestly aint got time to study code myself... so this is appreciated

**Comment by brendensoares** [comment]
:+1: team work. Love it.

**Comment by pedromorgan** [comment]
Openign this again cos It aint compalted...

**Comment by brendensoares** [comment]
@pedromorgan if it isn't complete then what is left and do you need more help?

**Comment by jeevatkm** [comment]
@pedromorgan I wonder, can I give it try what you need for docs? Please let me know.

**Comment by jeevatkm** [comment]
Since we are gonna work on revel/www#1, things will be taken care on that.

I'm closing this one.
