### ISSUE TITLE
Refactor path.* => filepath.* case by case

### ISSUE THREAD

**Issue by jeevatkm** [revel/cmd#46]
To make Revel more compatible with the targeted operating system-defined file paths. Goal is prevent OS related filesystem path issues.

Example:
From
```go
path.*
```
To
```go
filepath.*
```

**Comment by alkchr** [comment]
It's not `effort-minutes`. You'll see it will take much more time. Especially taking into account the fact Revel has a weak test coverage.
Apart from that, I'd like to warn you against using of `filepath.Join` everywhere thoughtlessly. Revel converts paths to import paths, saves paths in the template. When you start implementing this you'll see there is more benefit in using normalized (*nix style) form everywhere except when reading/writing stuff from/to the FS.

**Comment by jeevatkm** [comment]
@alkchr thanks for your suggestion and inputs. Yes I agree on test coverage, I'm planning work on test coverage after v0.13 release. It may not happen overnight but gradually we can increase it. If you can spare sometime for test coverage and submitting PR it would be great. I highly appreciate your help and effort. 

While working on PRs #14 and [1028](https://github.com/revel/revel/pull/1028) I already did my homework on this. Revel (`revel/revel` & `revel/cmd`) has 52+ reference to `path.*` also I had a look on import paths vs filesystem path manipulation case by case.

If you don't mind, I would like to take help from you for the testing.

**Comment by jeevatkm** [comment]
Started working on...

**Comment by jeevatkm** [comment]
Done!
