### ISSUE TITLE
undefined: revel.Walk on go get

### ISSUE THREAD

**Issue by xoen** [revel/cmd#53]
We use the `revel` command in this package to run the tests locally and on CircleCI.
It was working fine and it still works fine on my machine (with an older version of the packages) but it started to fail on CircleCI with the following error:

```
go get github.com/revel/cmd/revel
../.go_workspace/src/github.com/revel/cmd/harness/reflect.go:99: undefined: revel.Walk

go get github.com/revel/cmd/revel returned exit code 2

Action failed: go get github.com/revel/cmd/revel
```

We use `godep` for the rest of the dependencies but we install revel using `go get` which unfortunately can't get a specific/older version of a package.

Something must have changed recently. Any ideas or possible workarounds?

**Comment by xoen** [comment]
This could be caused by this: https://github.com/revel/cmd/pull/20 - Looks like `Walk` is on last version of revel but not on the old one we're using (`v0.12.0-1-g83c6204 / 83c62046c726f36daec7a28a335521f94b2561a6` according to Godep).

**Comment by xoen** [comment]
I'm trying to bump the `github.com/revel/revel` package (which is a bit scary). Tests seem to pass locally, hopefully it will not break anything.

Is [this config change](https://github.com/revel/revel/releases/tag/v0.13.0) the only required change on the code? Rename the `watcher = true` to `watch = true` in the `app.config` file?

**Comment by jeevatkm** [comment]
@xoen - You may know this, however I will describe it.

`revel.Walk` is introduced in `v0.13.0` release, if you have correct version of `revel/revel` & `cmd/revel` you will not have any issues.

Let's say you already have `github.com/revel/revel` and `github.com/revel/cmd/revel` on GOPATH then to get an updated version, please use go get with `-u` to get updated version.
```
go get -u github.com/revel/revel
go get -u github.com/revel/cmd/revel
```

Next, yes only breaking change is config name as described in the release notes.

Next, every `revel/revel` release will have corresponding release on `cmd/revel` repo. 

Can you please describe about scary part you mentioned above?

**Comment by xoen** [comment]
Hi @jeevatkm yep, `revel/cmd` is not part of our Godeps and we `go get` before running the tests. Unfortunately there is no way to `go get` a specific version therefore the issue (as I can't lock both packages).

I updated revel and so far we didn't see any problems (on staging).

**Comment by xoen** [comment]
BTW, I think this can be closed as upgrade `revel/revel` solves the problem.

**Comment by jeevatkm** [comment]
Thanks for your update, good to hear that. Just a thought may be you can try cloning specific version of `revel/cmd` from github tags corresponding to `revel/revel` as part of CI.
