### ISSUE TITLE
revel run fails on golang 1.7rc2

### ISSUE THREAD

**Issue by worg** [revel/cmd#59]
revel run fails with `-X flag requires argument of the form importpath.name=value` as the old syntax has been deprecated as mentioned on [Go 1.6 release notes](https://tip.golang.org/doc/go1.6#compiler) this change will land on 1.7

**Comment by jeevatkm** [comment]
This has been taken care on `develop` branch need to push for master. Please refer #51.

**Comment by jeevatkm** [comment]
@worg Thanks.
