### ISSUE TITLE
revel reinstall

### ISSUE THREAD

**Issue by pedromorgan** [revel/cmd#65]
This is a new command that..

Nukes all existance of a machine.. and reinstalls the whole revel platform to latest version..

Good luck but we are pre v.1.0 and therefor we can play right ;_)

Also we can do `revel switch` which makes it easy for me to crap out and start again ;-)

**Comment by notzippy** [comment]
Revel is modular, contained under one folder `$GOPATH/src/github.com/revel`Removing that folder will remove revel. No need for this
