### ISSUE TITLE
revel dev

### ISSUE THREAD

**Issue by pedromorgan** [revel/cmd#67]
the "dev" command will..

Check all the gh/revel/ repos and swithc modes

```
revel dev master  // stable
revel dev develop // next gen
```

the command checkout and switched modules, revel et all accordingly..

**Comment by pedromorgan** [comment]
Snag for any revel developer is to do the
# go get
and installed etc..

But as a developer one needs to
cd GOPATH/revel
and then checkout

So this command is a quick way to switch betdeen versions and branches ;-)

**Comment by pedromorgan** [comment]
## go get detect
if github url == https.. and branch == master

else
switch urls and branches

**Comment by notzippy** [comment]
This looks to be more of a job for documentation then something we really want to try to implement ourselves. If we are looking to do a release cycle month I think this can be closed, thoughts @pedromorgan ?

**Comment by pedromorgan** [comment]
yea will make docs

**Comment by pedromorgan** [comment]
Actually I do have thoughts..

The situation is that a standard revel install is via

go get github.com/revel/cmd
and this installs all revel/modules etc from master

Now say I want to switch to the develop "mode"
i need to enter the revel and modules (examples) and switch branch to develop

That's the idea in my head.. so i can then test latest develop branch, and switch back and forth at will

```
# lets have some fun
revel switch develop
revel run github.com/revel/revelframework.com

## a bug or someting so switch back
revel switch stable
revel run github.com/revel/revelframework.com

```

**Comment by pedromorgan** [comment]
and all it does in psuedo code
```
revel switch develop

for r in [revel, modules, examples] {
   cd GOPATH + github.com/revel/ + r
   git checkout <branch>
}
```

But develop can also have a switch to check git@ vs http checkout etc

**Comment by pedromorgan** [comment]
I think I need to create a new hackers page... to explain

branching problem et all
and namespace.. etc

But still think we need the 
```
revel update < upgrades to latest
revel dev < check developer info
```

And while were at it, we need a console to sak questions
```
cd github.com/me
revel wizz app
## enter project location
> github.com/me/

## Title [optional]
> 

enable jobs
enable ws
etc
```

**Comment by pedromorgan** [comment]
Oh and forgot..
```
revel example[s]
- chat
- booking
- facebook

revel example chat
> revel run github.com/revel/examples/shat
```

**Comment by notzippy** [comment]
I think what you are talking about here is some [package management tool](https://github.com/golang/go/wiki/PackageManagementTools) There are a lot and they can do what you ask. I think it is not necessary for us to reinvent the wheel on this.

**Comment by notzippy** [comment]
This is now happening
