### ISSUE TITLE
Skeleton app is using alert-error

### ISSUE THREAD

**Issue by notzippy** [revel/cmd#70]
Skeleton app is using `alert-error` instead of `alert-danger` css style for flash.html

**Comment by pedromorgan** [comment]
Fix is here https://github.com/revel/cmd/pull/69

Just needs someone to commit

**Comment by notzippy** [comment]
Looks good @pedromorgan added to next milestone build

**Comment by pedromorgan** [comment]
Fixed https://github.com/revel/cmd/commit/adcebf9acafc57dc325b11052ebbe990064bc413
