### ISSUE TITLE
Failed to parse port as integer: prod

### ISSUE THREAD

**Issue by Fyb3roptik** [revel/cmd#77]
This issue stems from the below pull:
https://github.com/revel/cmd/pull/56

Edge case of running:
revel run my-app prod

Causes this error to pop up. Quick fix is to do the following:

reve run my-app/ prod

**Comment by pedromorgan** [comment]
Sorry trying to triarge this.. but from what u explain..

```
// the / after my-app is a problem ?
revel run my-app/ prod
revel run my-app prod
```

**Comment by brendensoares** [comment]
@pedromorgan basically, if you don't have a slash in the first arg it interprets it as a run mode. [Related code 1](https://github.com/revel/cmd/blob/master/revel/run.go#L68):
```go
case 1:
	// Possibile combinations
	// 1. revel run [import-path]
	// 2. revel run [port]
	// 3. revel run [run-mode]
	if strings.Contains(args[0], "/") ||
```

[Related code 2](https://github.com/revel/cmd/blob/master/revel/run.go#L68):
```go
case 2:
	// Possibile combinations
	// 1. revel run [import-path] [run-mode]
	// 2. revel run [import-path] [port]
	// 3. revel run [run-mode] [port]
	if strings.Contains(args[0], "/") {):
```

**Comment by brendensoares** [comment]
@jeevatkm added this code in order to support `revel run` without explicitly providing an app's package path; it's determined by the current working directory and if it is nested inside the `$GOPATH`.

I think the fix for this issue is to not require the string format to include a slash, but rather to test the argument to see if it resolves to an actual path.

**Comment by brendensoares** [comment]
Closing this pending the merge of #78. Thanks @Fyb3roptik for your help in describing this bug.

**Comment by Fyb3roptik** [comment]
Glad I could help! Love the framework. Keep up the great work guys!
