### ISSUE TITLE
Remove error prone command line options

### ISSUE THREAD

**Issue by notzippy** [revel/cmd#80]
Multiple command line options are error prone and call for weird guesses in code (see #78 , #77) 
This proposal is to move the run mode and the port number into there own flagged parameters so they are not confused with the command or import path

**Comment by shawncatz** [comment]
we should work on rewriting the CLI, if we can do that as part of v0.16 that would be preferable. if not, we can rework the existing CLI for this issue.

**Comment by notzippy** [comment]
#81
