### ISSUE TITLE
revel cmd installation failing

### ISSUE THREAD

**Issue by paritosh90** [revel/cmd#94]
Hi,
Installation for revel cmd started failing from morning. This has affected our deployment. Please help. Below is log for same

> installing github.com/revel/cmd/revel ... 2017/06/07 20:29:39 failed installing packages: failed building package github.com/revel/cmd/revel, error: # github.com/revel/modules/testrunner/app/controllers
> ../../modules/testrunner/app/controllers/testrunner.go:124: revel.MainTemplateLoader.TemplateLang undefined (type *revel.TemplateLoader has no field or method TemplateLang)
> , output: %!s(MISSING): exit status 2 [exit status 2 github.com/dkulchenko/bunch/packages.go:234: failed building package github.com/revel/cmd/revel, error: # github.com/revel/modules/testrunner/app/controllers
> ../../modules/testrunner/app/controllers/testrunner.go:124: revel.MainTemplateLoader.TemplateLang undefined (type *revel.TemplateLoader has no field or method TemplateLang)
> , output: %!s(MISSING) github.com/dkulchenko/bunch/packages.go:643: ]

**Comment by notzippy** [comment]
We just updated to revel to v0.16.0, it looks like some of your packages are older. Can you try a `go get -u gitub.com/revel/cmd/revel` and see if that works ?

**Comment by paritosh90** [comment]
@notzippy currently we are using revel v0.14.0 and our golang version is go1.6. If I update my revel package then we have to upgrade our go version as well to go1.7. This does not look like an viable option to me and with every new changes it is difficult to upgrade to new version.
Is there any other work around? 
Also why there is no backward compatibility (as new fixes/changes should not affect older version of revel).

**Comment by notzippy** [comment]
Go 1.6 will be fine for revel.

**Comment by paritosh90** [comment]
For revel v0.16.0?

**Comment by notzippy** [comment]
Yes, I just checked and verified this, I will create a PR to continue to be compatible for go 1.6

**Comment by paritosh90** [comment]
@notzippy: will revel v0.14.0 be compatible anymore? As installation is failing.

**Comment by notzippy** [comment]
Version 15 likely had a number of changes that may affect your application. When we do a 1.0 release, we will maintain full backwards compatibility with that version. 

When you deploy you should be deploying a prebuilt version (something compiled with `revel build` command) You can downgrade the revel in your gopath by going into each github.com/revel/* repo folder and checking out the tag `v0.14.0`

**Comment by gardner** [comment]
Similar issue. I had older versions of golang installed as well.
```
$ go get github.com/revel/cmd/revel
# github.com/revel/modules/testrunner/app/controllers
../../../golang/src/github.com/revel/modules/testrunner/app/controllers/testrunner.go:124: revel.MainTemplateLoader.TemplateLang undefined (type *revel.TemplateLoader has no field or method TemplateLang)
$
```

Solved with: `go get -u github.com/revel/cmd/revel`
